name: Update dependencies and generate new lockfile

on:
  workflow_dispatch:

jobs:
  lockfile-generator:
    runs-on: ubuntu-latest
    env:
      RELEASES_GPG_PASSPHARSE: ${{ secrets.RELEASES_GPG_PASSPHARSE }}
      RELEASES_GPG_KEY: ${{ secrets.RELEASES_GPG_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_SERVICE_ACCOUNT_API_KEY}}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Git
        run: curl -fsSL https://github.com/code-server-boilerplates/charts/raw/main/scripts/setup-ci | bash
      - name: Update npmjs
        run: npm i -g npm@latest
      - name: Run install CI
        run: npm install && npm ci || true
      - name: Attempt to upgrade dependencies
        run: |
          echo "::addgroup::List outdated packages"
          npm outdated
          echo "::endgroup::"

          echo "::addgroup::Upgrade dependencies"
          npm update
          echo "::endgroup::"
      - name: Stage changes and check status
        run: |
          git add .

          echo "::addgroup::Check pending changes"
          git status -s
          echo "::endgroup::"
          sleep 30
      - name: Generate pull request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
          author: Recap Time Bot <releases@madebythepins.tk>
          committer: Recap Time Bot <releases@madebythepins.tk>
          signoff: true
          commit-message: Update npm dependencies and lockfile
          branch: update-dependencies-npmjs
          labels: |
            packages/nodejs-npm
            dependencies
          reviewers: ${{ github.actor }}
          assignees: ${{ github.actor }}
          title: Update npmjs lockfiles and dependencies
          body: |
            Your PR has been successfully generated to update dependencies and lockfile. Please wait while Vercel is doing an build for our website to ensure there will be no breaking changes to be merged to production.

            When the build status goes green, approve and add `Ready to Ship` label to automagically merge.
            Before merging, make sure you read the changelog of these updated packages before proceeding.

            ---

            _This PR is generated using [this GitHub action](https://github.com/peter-evans/create-pull-request), btw._
      - name: Extract PR link
        run: |
          echo "An PR has been generated to update npm dependencies. Go to ${{ steps.cpr.outputs.pull-request-url }} to complete the merge request workflow."
