name: Generate Yarn lockfile

on:
  workflow_dispatch:

jobs:
  lockfile-generator:
    runs-on: ubuntu-latest
    env:
      RELEASES_GPG_PASSPHARSE: ${{ secrets.RELEASES_GPG_PASSPHARSE }}
      RELEASES_GPG_KEY: ${{ secrets.RELEASES_GPG_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_SERVICE_ACCOUNT_API_KEY}}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Git
        run: curl -fsSL https://github.com/code-server-boilerplates/charts/raw/main/scripts/setup-ci | bash
      - name: Update npmjs
        run: npm i -g npm@latest
      - name: Setup Yarn Berry
        shell: bash
        run: |
          git switch -c update-lockfiles-$GITHUB_RUN_ID origin/master
      - name: Run install CI
        run: npm ci
      - name: Attempt to upgrade dependencies
        run: |
          echo "::addgroup::List outdated packages"
          npm outdated
          echo "::endgroup::"

          echo "::addgroup::Upgrade dependencies"
          npm update
          echo "::endgroup::"
      - name: Stage changes and check status
        run: |
          git add .

          echo "::addgroup::Check pending changes"
          git status -s
          echo "::endgroup::"
          sleep 30
      - name: Commit changes
        run: |
          git commit -m "Updated npmjs lockfiles and dependencies" --signoff
          git push origin update-lockfiles-$GITHUB_RUN_ID
