name: Generate Yarn lockfile

on:
  workflow_dispatch:

jobs:
  lockfile-generator:
    runs-on: ubuntu-latest
    env:
      RELEASES_GPG_PASSPHARSE: ${{ secrets.RELEASES_GPG_PASSPHARSE }}
      RELEASES_GPG_KEY: ${{ secrets.RELEASES_GPG_KEY }}
      UPGRADE_LOCAL_YARNPKG_BINARY: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_SERVICE_ACCOUNT_API_KEY}}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Git
        run: curl -fsSL https://github.com/code-server-boilerplates/charts/raw/main/scripts/setup-ci | bash
      - name: Install Yarn
        run: npm i -g yarn
      - name: Setup Yarn Berry
        shell: bash
        run: |
          git checkout update-lockfiles
          [ ! -d .yarn/versions ] && yarn set version berry || [ -d .yarn/versions ] && [[ $UPGRADE_LOCAL_YARNPKG_BINARY != "" ]] && yarn set version latest
      - name: Run install CI
        run: yarn install
      - name: Attempt to upgrade dependencies
        run: |
          yarn up gatsby react react-dom smooth-doc || true
      - name: Stage changes and check status
        run: git add . && git status
      - name: Commit changes
        run: |
          git commit -m "Updated Yarn lockfiles and stuff" --signoff
          git push origin update-lockfiles
